## Pandas Tutorial 

Pandas is an open-source data maniplation and analysis library for Python.It provides data structures like series (1D labeled array) and Dataframe (2D labeled data structure), which are designed for structure data, such as tables.

 It is widely used for tasks such as data cleaning, preparation, exploration, and analysis.


### Here are the two key structures in Pandas:

1.	__Series__: A one-dimensional labeled array capable of holding any data type (integers, strings, floating-point numbers, etc.). It is similar to a column in a table or a single list in Python.


2.	__DataFrame__: A two-dimensional labeled data structure, similar to a table in a database or a spreadsheet, with rows and columns. Each column in a DataFrame is a Series.


#### Example:

In [1]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['John', 'Jane', 'Tom'],
        'Age': [23, 24, 22],
        'City': ['New York', 'Paris', 'London']}

df = pd.DataFrame(data)
print(df)

   Name  Age      City
0  John   23  New York
1  Jane   24     Paris
2   Tom   22    London

In [1]:
# First step is to import pandas :

import pandas as pd
import numpy as np

In [2]:
# Importing and Exporting data :
# File can be read using the file name as string :

df = pd.read_excel(r'Attribute DataSet.xlsx')

In [3]:
# Creating an object as a DataFrame :

df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [4]:
# Check the type of an object :

type(df)

pandas.core.frame.DataFrame

In [5]:
# Playing with dataframe :

df1 = pd.read_excel('Attribute DataSet.xlsx', sheet_name = 'Sheet2', header = None)

In [6]:
df1

          0     1     2
0  sefasfga   gfh    df
1      gadf    fg   bdf
2      gadf   nfg   bdf
3      sdfh   nfg    xc
4      sfdg    cx   bdf
5      hfgj   nfg   cxv
6       fgd    xc  bxcv
7         j  nbxc     b
8       fgj    fg  cvbx

In [7]:
# Read an Excel file into a pandas DataFrame :

df1 = pd.read_excel('Attribute DataSet.xlsx', sheet_name = 'Sheet2', header = None, names = ['A','B','C'])

In [8]:
df1

          A     B     C
0  sefasfga   gfh    df
1      gadf    fg   bdf
2      gadf   nfg   bdf
3      sdfh   nfg    xc
4      sfdg    cx   bdf
5      hfgj   nfg   cxv
6       fgd    xc  bxcv
7         j  nbxc     b
8       fgj    fg  cvbx

In [9]:
# Return the first 'n' rows(default 5) :

df1.head()

          A    B    C
0  sefasfga  gfh   df
1      gadf   fg  bdf
2      gadf  nfg  bdf
3      sdfh  nfg   xc
4      sfdg   cx  bdf

In [10]:
# Returns the last 'n' rows(default 5) :

df1.tail()

      A     B     C
4  sfdg    cx   bdf
5  hfgj   nfg   cxv
6   fgd    xc  bxcv
7     j  nbxc     b
8   fgj    fg  cvbx

In [11]:
# Read a comma-separated values (csv) file into DataFrame :

pd.read_csv('haberman.csv', header= None, names= ['Age',"Patient's year of operation",'No of postive','Survival status'] )

     Age  Patient's year of operation  No of postive  Survival status
0     30                           64              1                1
1     30                           62              3                1
2     30                           65              0                1
3     31                           59              2                1
4     31                           65              4                1
..   ...                          ...            ...              ...
301   75                           62              1                1
302   76                           67              0                1
303   77                           65              3                1
304   78                           65              1                2
305   83                           58              2                2

[306 rows x 4 columns]

In [12]:
# Read a comma-separated values (csv) file into DataFrame(if sep is different) :

pd.read_csv('haberman1.csv',sep= '@')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [13]:
# Read CSV file using file path :

pd.read_csv('https://raw.githubusercontent.com/Opensourcefordatascience/Data-sets/master/sexual_comp.csv')

      Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  score  gender  age
0      1   1   2   1   1   4   2   3   3    1     19       1   41
1      2   1   1   1   1   2   1   2   1    2     14       1   50
2      2   1   1   1   1   4   1   1   1    2     15       1   23
3      2   1   1   1   1   4   1   1   1    4     17       1   42
4      1   1   1   1   1   2   1   1   1    1     11       2   36
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...    ...     ...  ...
3371   2   1   1   2   1   2   1   2   1    2     15       1   22
3372   4   4   4   3   3   4   4   4   4    3     37       1   49
3373   2   1   2   1   1   2   2   1   1    1     14       1   44
3374   3   2   2   2   2   4   2   3   3    3     26       1   30
3375   2   1   2   1   3   4   3   4   4    4     28       2   40

[3376 rows x 13 columns]

In [14]:
# Read HTML tables into a "list" of "DataFrame" objects :

pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

[        Rk             Player   Age Team  Pos     G    GS      MP     FG  \
 0      1.0       James Harden  25.0  HOU   SG  81.0  81.0  2981.0  647.0
 1      2.0      Stephen Curry  26.0  GSW   PG  80.0  80.0  2613.0  653.0
 2      3.0  Russell Westbrook  26.0  OKC   PG  67.0  67.0  2302.0  627.0
 3      4.0       LeBron James  30.0  CLE   SF  69.0  69.0  2493.0  624.0
 4      5.0     Damian Lillard  24.0  POR   PG  82.0  82.0  2925.0  590.0
 ..     ...                ...   ...  ...  ...   ...   ...     ...    ...
 647  489.0        Malcolm Lee  24.0  PHI   SG   1.0   0.0     2.0    0.0
 648  490.0        Kalin Lucas  25.0  MEM   PG   1.0   0.0     6.0    0.0
 649  491.0       Ronny Turiaf  32.0  MIN    C   2.0   0.0    19.0    0.0
 650  492.0         David Wear  24.0  SAC   PF   2.0   0.0     7.0    0.0
 651    NaN     League Average   NaN  NaN  NaN   NaN   NaN     NaN    NaN

         FGA  ...    ORB    DRB    TRB    AST    STL   BLK    TOV     PF  \
 0    1470.0  ...   75.0  384.0  459.0  565.0  154.0  60.0  321.0  208.0
 1    1341.0  ...   56.0  285.0  341.0  619.0  163.0  16.0  249.0  158.0
 2    1471.0  ...  124.0  364.0  488.0  574.0  140.0  14.0  293.0  184.0
 3    1279.0  ...   51.0  365.0  416.0  511.0  109.0  49.0  272.0  135.0
 4    1360.0  ...   49.0  329.0  378.0  507.0   97.0  21.0  222.0  164.0
 ..      ...  ...    ...    ...    ...    ...    ...   ...    ...    ...
 647     1.0  ...    0.0    0.0    0.0    0.0    0.0   0.0    0.0    0.0
 648     1.0  ...    0.0    0.0    0.0    0.0    1.0   0.0    0.0    1.0
 649     0.0  ...    0.0    1.0    1.0    2.0    0.0   0.0    0.0    0.0
 650     2.0  ...    2.0    0.0    2.0    1.0    0.0   0.0    0.0    1.0
 651     NaN  ...    NaN    NaN    NaN    NaN    NaN   NaN    NaN    NaN

         PTS                 Awards
 0    2217.0          MVP-2,AS,NBA1
 1    1900.0          MVP-1,AS,NBA1
 2    1886.0          MVP-4,AS,NBA2
 3    1743.0  MVP-3,DPOY-13,AS,NBA1
 4    1720.0                     AS
 ..      ...                    ...
 647     0.0                    NaN
 648     0.0                    NaN
 649     0.0                    NaN
 650     0.0                    NaN
 651     NaN                    NaN

 [652 rows x 31 columns],
         Rk          Player   Age Team  Pos     G    GS     MP     FG    FGA  \
 0      1.0    LeBron James  30.0  CLE   SF  20.0  20.0  844.0  227.0  544.0
 1      2.0   Stephen Curry  26.0  GSW   PG  21.0  21.0  826.0  200.0  439.0
 2      3.0    James Harden  25.0  HOU   SG  17.0  17.0  636.0  129.0  294.0
 3      4.0   Klay Thompson  24.0  GSW   SG  21.0  21.0  761.0  149.0  334.0
 4      5.0   Blake Griffin  25.0  LAC   PF  14.0  14.0  557.0  140.0  274.0
 ..     ...             ...   ...  ...  ...   ...   ...    ...    ...    ...
 204  205.0   Joel Freeland  27.0  POR    C   2.0   0.0    7.0    0.0    0.0
 205  206.0      Alonzo Gee  27.0  POR   SF   1.0   0.0    3.0    0.0    0.0
 206  207.0      Jeff Ayres  27.0  SAS   PF   3.0   0.0   12.0    0.0    1.0
 207  208.0   Rasual Butler  35.0  WAS   SF   2.0   0.0    7.0    0.0    1.0
 208    NaN  League Average   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN

      ...   ORB    DRB    TRB    AST   STL   BLK   TOV    PF    PTS  Awards
 0    ...  37.0  189.0  226.0  169.0  33.0  21.0  82.0  58.0  601.0     NaN
 1    ...  20.0   85.0  105.0  134.0  39.0   3.0  82.0  47.0  594.0     NaN
 2    ...  12.0   85.0   97.0  128.0  28.0   7.0  77.0  49.0  462.0     NaN
 3    ...   9.0   72.0   81.0   54.0  16.0  19.0  41.0  64.0  391.0     NaN
 4    ...  38.0  140.0  178.0   86.0  14.0  14.0  45.0  43.0  357.0     NaN
 ..   ...   ...    ...    ...    ...   ...   ...   ...   ...    ...     ...
 204  ...   0.0    1.0    1.0    0.0   1.0   0.0   0.0   0.0    0.0     NaN
 205  ...   0.0    1.0    1.0    1.0   0.0   0.0   0.0   0.0    0.0     NaN
 206  ...   0.0    3.0    3.0    2.0   0.0   0.0   0.0   0.0    0.0     NaN
 207  ...   0.0    1.0    1.0    1.0   0.0   0.0   0.0   2.0    0.0     NaN
 208  ...   NaN    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN     NaN

 [209 rows x 31 columns]]

In [15]:
a = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [16]:
len(a)

2

In [17]:
a[0]

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,75.0,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,56.0,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,124.0,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,51.0,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,49.0,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,2.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Convert a JSON string to pandas object :

pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,author_association,active_lock_reason,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59880,2543824516,I_kwDOAA0YD86Xn66E,59880,DOC: defaults in method signature vs description,...,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59879,2543054802,I_kwDOAA0YD86Xk-_S,59879,BUG (string dtype): looking up missing value i...,...,MEMBER,NaN,https://github.com/pandas-dev/pandas/issues/59...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59878,2543042800,PR_kwDOAA0YD858ZD-O,59878,DOC: Add doc for Series.dt.to_timestamp to dat...,...,NONE,NaN,- [x] closes #59671\r\n- [x] All [code checks ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59877,2542255501,I_kwDOAA0YD86Xh72N,59877,ENH: Adding `\cline`s to LaTeX table if index ...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59876,2542059976,I_kwDOAA0YD86XhMHI,59876,BUG: `pd.options.display.float_format` did not...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59875,2541878494,PR_kwDOAA0YD858VDrW,59875,TST: update frame method quantile tests,...,MEMBER,NaN,xref https://github.com/pandas-dev/pandas/issu...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59874,2541311508,I_kwDOAA0YD86XeVYU,59874,ENH: Droping consecutive duplicates,...,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59873,2541083390,PR_kwDOAA0YD858SY-R,59873,Fix Docstring Issues for pandas.Series.sparse...,...,NONE,NaN,This pull request addresses the following issu...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59872,2541031822,PR_kwDOAA0YD858SO5L,59872,"DOC: fix SA01, ES01 for pandas.errors.EmptyDat...",...,CONTRIBUTOR,NaN,related to #58063\r\n\r\nfixes\r\n\r\n```\r\np...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59871,2540860338,PR_kwDOAA0YD858RnWD,59871,"DOC: fix RT03, ES01 for pandas.core.resample.R...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.core.resample.Resam...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59869,2540829676,PR_kwDOAA0YD858RgKN,59869,"DOC: fix RT03, ES01 for pandas.core.groupby.Da...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.core.groupby.DataFr...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59868,2540807603,PR_kwDOAA0YD858RbBC,59868,DOC: fix RT03 for pandas.date_range,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.date_range RT03\r\n```,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59867,2540739580,PR_kwDOAA0YD858RLFn,59867,"DOC: fix SA01, ES01 for pandas.arrays.Interval...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.arrays.IntervalArra...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59866,2540728735,PR_kwDOAA0YD858RIkj,59866,DOC: fix SA01 for pandas.arrays.BooleanArray,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.arrays.BooleanArray...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59865,2540720636,PR_kwDOAA0YD858RGrm,59865,"DOC: fix SA01, ES01 for pandas.api.types.is_ob...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.api.types.is_object...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59864,2540711558,PR_kwDOAA0YD858REje,59864,DOC: fix SA01 for pandas.api.types.is_list_like,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.api.types.is_list_l...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59863,2540657789,PR_kwDOAA0YD858Q4sy,59863,DOC: fix SA01 for pandas.api.types.is_interval...,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.api.types.is_interv...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59862,2540652442,PR_kwDOAA0YD858Q3ni,59862,DOC: fix SA01 for pandas.api.types.is_int64_dtype,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.api.types.is_int64_...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59861,2540650521,PR_kwDOAA0YD858Q3N_,59861,"DOC: fix SA01, ES01 for pandas.api.types.is_fl...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.api.types.is_float_...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59860,2540647739,PR_kwDOAA0YD858Q2p1,59860,"DOC: fix SA01, ES01 for pandas.Timedelta.to_ti...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.Timedelta.to_timede...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59859,2540645450,PR_kwDOAA0YD858Q2Mh,59859,"DOC: fix SA01, ES01 for pandas.Series.sparse.s...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.Series.sparse.sp_va...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59858,2540643338,PR_kwDOAA0YD858Q1w4,59858,DOC: fix SA01 for pandas.Series.sparse.fill_value,...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.Series.sparse.fill_...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59857,2540639252,PR_kwDOAA0YD858Q08e,59857,"DOC: fix SA01, ES01 for pandas.RangeIndex.step",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.RangeIndex.step SA0...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59856,2540637013,PR_kwDOAA0YD858Q0fp,59856,"DOC: fix SA01, ES01 for pandas.tseries.offsets...",...,CONTRIBUTOR,NaN,fixes\r\n\r\n```\r\npandas.tseries.offsets.Sem...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59855,2539835745,PR_kwDOAA0YD858OTlS,59855,DOC: Fix inconsistent and incomplete documenta...,...,NONE,NaN,- [x] closes #58338\r\n- [x] All [code checks ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59854,2539782487,PR_kwDOAA0YD858OIEh,59854,String dtype: allow string dtype for non-raw a...,...,MEMBER,NaN,https://github.com/pandas-dev/pandas/pull/5510...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59853,2539768115,PR_kwDOAA0YD858OE19,59853,String dtype: implement sum reduction,...,MEMBER,NaN,Based on the feedback in https://github.com/pa...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59852,2539749635,PR_kwDOAA0YD858OAsp,59852,typo,...,CONTRIBUTOR,NaN,_cf_: https://github.com/pandas-dev/pandas/pul...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/59850,2538915099,PR_kwDOAA0YD858LG6s,59850,Separate out examples - pandas.str.is methods,...,NONE,NaN,- [x] closes #59806\r\n- [x] All [code checks ...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/59846,2538152238,I_kwDOAA0YD86XSSEu,59846,BUG: Automatic change of color when the plot t...,...,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,NaN,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN

In [19]:
js = pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

In [20]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'body', 'closed_by', 'reactions', 'timeline_url',
       'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
      dtype='object')

In [21]:
js['user'][0]

{'login': 'kuraga',
 'id': 1063219,
 'node_id': 'MDQ6VXNlcjEwNjMyMTk=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/1063219?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/kuraga',
 'html_url': 'https://github.com/kuraga',
 'followers_url': 'https://api.github.com/users/kuraga/followers',
 'following_url': 'https://api.github.com/users/kuraga/following{/other_user}',
 'gists_url': 'https://api.github.com/users/kuraga/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/kuraga/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/kuraga/subscriptions',
 'organizations_url': 'https://api.github.com/users/kuraga/orgs',
 'repos_url': 'https://api.github.com/users/kuraga/repos',
 'events_url': 'https://api.github.com/users/kuraga/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/kuraga/received_events',
 'type': 'User',
 'site_admin': False}

In [22]:
df = pd.read_excel(r'Attribute DataSet.xlsx')

In [23]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [24]:
# Convert the object to a JSON string :

df.to_json('text2.json')

In [25]:
pwd (# present working directory)

'/Users/sushantyadav'

In [26]:
# Convert the object to a CSV file :

df.to_csv('/Users/sushantyadav/test0123.csv', sep = '@', index = False)

In [ ]:
df.dropna()